Update index project description
artefactual-labs/enduro pull request #619
Opened 2024-07-02 19:56 UTC by fiver-watson

Based on a request from BUD. Change summary: 

* Remove mention of "proof of concept" from documentation index
* Mention both a3m and Archivematica
* Bring overall description more in-line with current SDPS version of Enduro

2024-07-02 20:07 UTC, Jennoit commented
Thanks @fiver-watson - I would add only that (if it is in-line with current SDPS/Enduro docs) this tool is being used in production (maybe that is implied by removing PoC).

2024-07-02 21:57 UTC, jraddaoui requested changes
@fiver-watson This version doesn't work with a3m.

2024-07-03 12:07 UTC, fiver-watson commented
Thanks @Jennoit  and @jraddaoui ! I have tried to address your feedback with a small update. Let me know if this addresses it.

2024-07-03 16:15 UTC, jraddaoui approved these changes
Thanks!

2024-07-04 12:22 UTC, merged

2024-07-04 15:04 UTC, Jennoit commented
It addresses my request. Thanks.

2024-07-04 16:00 UTC, fiver-watson commented
Great! We have also made the descriptions more consistent in other Enduro forks, like: 

* https://github.com/artefactual-sdps/enduro/blob/main/docs/src/index.md
* https://github.com/artefactual-sdps/enduro/blob/main/README.md

And the README in this repo: 

* https://github.com/artefactual-labs/enduro/blob/main/README.md